"use client";

import { useEffect, useState } from 'react'
import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from '@/app/Navbar/page'
import BottomNavigation from '@/app/BottomNavigation/page'
import Footer from '@/app/Footer/page'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [isMobileOrTabletDevice, setIsMobileOrTabletDevice] = useState(false);

  // Function to check if the user is on a mobile or tablet device
  const checkDeviceType = () => {
    if (typeof window !== 'undefined') {
      const userAgent = window.navigator.userAgent.toLowerCase();
      setIsMobileOrTabletDevice(
        /android|webos|iphone|ipad|ipod|blackberry|iemobile|opera mini/i.test(userAgent)
      );
    }
  };

  useEffect(() => {
    checkDeviceType();
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        {isMobileOrTabletDevice ? <BottomNavigation /> : <Navbar />}
        {children}
        <Footer />
      </body>
    </html>
  )
}
